# Works with kitchen-ec2 v0.8.0
---
driver:
  name: ec2
  security_group_ids: ['sg-45fdda28']
  region: us-east-1
  aws_ssh_key_id: test-kitchen
  require_chef_omnibus: false
  instance_type: m3.large
  tags:
    kitchen-test: "appliance-docker"

transport:
  ssh_key: <%= ENV['SSH_KEY'] %>
  username: ec2-user

provisioner:
  name: shell

platforms:
  - name: amazon-linux-2
    driver:
      image_id: <%= ENV['AMI_ID'] %>
      block_device_mappings:
        - device_name: /dev/xvda
          ebs:
            volume_size: 20
            delete_on_termination: true

suites:
  - name: default
